services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=avia_tickets'
      - 'MYSQL_PASSWORD=1'
      - 'MYSQL_ROOT_PASSWORD=pwd'
      - 'MYSQL_USER=noo8xl'
    ports:
      - '3306'
