# Auth endpoints only

### Singup new customer with correct data
POST http://localhost:9832/auth/signUp/
Content-Type: application/json

{
  "name": "testName",
  "email": "email@example.com",
  "password": "qwerty123456"
}

### Check customer 2fa status
GET http://localhost:9832/auth/check-2fa/email@example.com/
Content-Type: application/json

### Sign in without 2fa
POST http://localhost:9832/auth/signIn/
Content-Type: application/json

{
  "name": "testName",
  "email": "email@example.com",
  "password": "qwerty123456",
  "twoStep": false,
  "code": null
}

### Sign in with enabled 2fa
POST http://localhost:9832/auth/signIn/
Content-Type: application/json

{
  "name": "testName",
  "email": "email@example.com",
  "password": "qwerty123456",
  "twoStep": true,
  "code": "12345"
}

### Forgot password
PATCH http://localhost:9832/auth/forgot-password/email@example.com/
Content-Type: application/json


### Sign in with new password (get it in the console)
POST http://localhost:9832/auth/signIn/
Content-Type: application/json

{
  "name": "testName",
  "email": "email@example.com",
  "password": "<insert new pwd here>",
  "twoStep": false,
  "code": null
}

### Sign in with enabled 2fa and WRONG code
POST http://localhost:9832/auth/signIn/
Content-Type: application/json

{
  "name": "testName",
  "email": "email@example.com",
  "password": "qwerty123456",
  "twoStep": true,
  "code": "54321"
}

### Sign up with WRONG name data
POST http://localhost:9832/auth/signUp/
Content-Type: application/json

{
  "name": "wrg",
  "email": "email@example.net",
  "password": "123qwerty"
}

### Sign up with WRONG email data
POST http://localhost:9832/auth/signUp/
Content-Type: application/json

{
  "name": "testName",
  "email": 1,
  "password": "qwerty123456"
}

### Sign up with WRONG password data
POST http://localhost:9832/auth/signUp/
Content-Type: application/json

{
  "name": "testName",
  "email": "email@example.com",
  "password": "js666"
}

