# Customer area endpoints only

### Get customer by email with correct data
GET http://localhost:9832/customer/get-customer-by-email/email@example.com/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbEBleGFtcGxlLmNvbSIsImlhdCI6MTcyMjYyNzEzNSwiZXhwIjoxNzIyNjI4NTc1fQ.AOyjbmgZmkow3P5i6nwD6542Ag26oGHNssvsmVE9_9o


### Get customer by id with correct data
GET http://localhost:9832/customer/get-customer-by-id/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbEBleGFtcGxlLmNvbSIsImlhdCI6MTcyMjYyODA1MSwiZXhwIjoxNzIyNjI5NDkxfQ.tVVrQCleni8OzxhLe7o13_GNcmyuJ_uw0G8hMxTkiBc


### Get customer by email with WRONG data
GET http://localhost:9832/customer/get-customer-by-email/email@wrong.data/
Content-Type: application/json

### Get customer by id with WRONG data
GET http://localhost:9832/customer/get-customer-by-id/9283/
Content-Type: application/json

### Change customer password with correct data
PATCH http://localhost:9832/customer/change-password/
Content-Type: application/json

{
  "email": "email@example.com",
  "pwd": "some123newPWD"
}

### Change customer password with WRONG data
PATCH http://localhost:9832/customer/change-password/
Content-Type: application/json

{
  "email": "email@example.com",
  "pwd": "13"
}

### Change customer 2fa status
PATCH http://localhost:9832/customer/change-2fa-status/
Content-Type: application/json

{
  "customerId": 1,
  "email": "email@example.com",
  "status": false
}

### Get list of customers as ADMIN
GET http://localhost:9832/customer/get-customer-list/0/10/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbEBleGFtcGxlLmNvbSIsImlhdCI6MTcyMjYyNzgyMywiZXhwIjoxNzIyNjI5MjYzfQ.S555tbkfWg8QYi8ipKrPHjLj-Zy9gubNk0nwFc3_ZNE


### Get list of customers with WRONG permission
GET http://localhost:9832/customer/get-customer-list/0/-10/
Content-Type: application/json
Authorization: Bearer

### Update customer details with correct data
PUT http://localhost:9832/customer/update/
Content-Type: application/json
Authorization: Bearer

{
  "id": 1,
  "name": "updatedName",
  "email": "email@example.com",
  "password": "myNew123pwd"
}