# Customer area endpoints only

### Get customer by email with correct data
GET http://localhost:9832/customer/get-customer-by-email/email@example.com/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbEBleGFtcGxlLmNvbSIsImlhdCI6MTcyNDA5NDUxMSwiZXhwIjoxNzI0MDk1OTUxfQ.XRNDOxa4wE7tXqXOg8JhVPE4jtB3lpxf-wkIAgztFsM

### Get customer by id with correct data
GET http://localhost:9832/customer/get-customer-by-id/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbEBleGFtcGxlLmNvbSIsImlhdCI6MTcyNDA5NTM3MywiZXhwIjoxNzI0MDk2ODEzfQ.NN4M05wL2-jaKndPOpIJP-YkLQQN3KW55uLOt6rFL2A

### Get customer by email with WRONG data
GET http://localhost:9832/customer/get-customer-by-email/email@wrong.data/
Content-Type: application/json

### Get customer by id with WRONG data
GET http://localhost:9832/customer/get-customer-by-id/9283/
Content-Type: application/json

### Change customer password with correct data
PATCH http://localhost:9832/customer/update/change-password/
Content-Type: application/json

{
  "email": "email@example.com",
  "pwd": "some123newPWD"
}

### Change customer password with WRONG data
PATCH http://localhost:9832/customer/update/change-password/
Content-Type: application/json

{
  "email": "email@example.com",
  "pwd": "13"
}

### Change customer 2fa status
PATCH http://localhost:9832/customer/update/change-2fa-status/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbEBleGFtcGxlLmNvbSIsImlhdCI6MTcyNDYwNDYwNSwiZXhwIjoxNzI0NjA2MDQ1fQ.R4bu_h-iqgYSt8drySnv2GWESwZvrs7Y7GjW-QkobFE


{
  "customerId": 1,
  "type": "telegram",
  "telegramId": "949347540",
  "email": "email@example.com",
  "status": false
}

### Get list of customers as ADMIN
GET http://localhost:9832/customer/get-customer-list/0/10/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbEBleGFtcGxlLmNvbSIsImlhdCI6MTcyNDYwMTcyOSwiZXhwIjoxNzI0NjAzMTY5fQ.ev_MLxWJ7SQvf99OfIk-7jlaPoq5JCackH7F0hx2ANA

### Get list of customers with WRONG permission
GET http://localhost:9832/customer/get-customer-list/0/-10/
Content-Type: application/json
Authorization: Bearer

### Update customer details with correct data
PUT http://localhost:9832/customer/update/
Content-Type: application/json
Authorization: Bearer

{
  "id": 1,
  "name": "updatedName",
  "email": "email@example.com",
  "password": "myNew123pwd"
}

### Delete customer as ADMIN
DELETE http://localhost:9832/customer/delete/2/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbWFpbEBleGFtcGxlLmNvbSIsImlhdCI6MTcyNDE2MzI3NywiZXhwIjoxNzI0MTY0NzE3fQ._UDQrrp6jwHWeeKiDzTC7vZL5X4frfgWbm5qlX8W-Hg

